In [20]:
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Layer, Reshape
import tensorflow as tf
import numpy as np
from load_data import x_test

In [9]:
latent_representation_dim = 4
layer_nodes = 4

In [19]:
conv1 = Conv2D(32, 3, activation='relu')
flatten = Flatten()
layer1 = Dense(layer_nodes, activation="relu")
layer2 = Dense(layer_nodes, activation="relu")
means = Dense(latent_representation_dim, activation="linear")
log_stds = Dense(latent_representation_dim, activation="linear")
L_dash = Dense(latent_representation_dim**2, activation=Reshape((latent_representation_dim, latent_representation_dim)))

In [22]:
batch_size=32
minitest = x_test[0:batch_size, :, :]#.flatten()
layer2_ = layer2(layer1(flatten(conv1(minitest))))
L_dash_ = L_dash(layer2_)

In [25]:
L_mask = np.ones((latent_representation_dim, latent_representation_dim))
L_mask = np.tril(L_mask, k=-1)
L_mask

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

In [26]:
L_dash_.shape

TensorShape([32, 4, 4])

In [27]:
L_dash_ * L_mask

<tf.Tensor: shape=(32, 4, 4), dtype=float32, numpy=
array([[[-0.        , -0.        , -0.        , -0.        ],
        [ 0.00103968,  0.        , -0.        , -0.        ],
        [ 0.00039915,  0.00073707, -0.        , -0.        ],
        [ 0.00090894, -0.00058759,  0.00034319,  0.        ]],

       [[-0.        , -0.        , -0.        , -0.        ],
        [ 0.05551314,  0.        , -0.        , -0.        ],
        [ 0.02131239,  0.03935575, -0.        , -0.        ],
        [ 0.04853278, -0.03137438,  0.01832452,  0.        ]],

       [[-0.        , -0.        , -0.        , -0.        ],
        [ 0.0476375 ,  0.        , -0.        , -0.        ],
        [ 0.0182888 ,  0.03377236, -0.        , -0.        ],
        [ 0.04164745, -0.02692331,  0.01572483,  0.        ]],

       [[-0.        , -0.        , -0.        , -0.        ],
        [ 0.04041826,  0.        , -0.        , -0.        ],
        [ 0.01551722,  0.02865431, -0.        , -0.        ],
        [ 0.